# Generated by Django 4.1.1 on 2022-10-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(blank=True, default='', null=True)),
                ('username', models.TextField(blank=True, default=None, null=True)),
                ('dialog', models.TextField(default='start')),
                ('temp', models.TextField(blank=True, default='')),
            ],
        ),
    ]
