# Generated by Django 4.1.1 on 2022-10-03 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='numbers_test_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='numbers_test_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 13, 45, 12, 74129)),
        ),
    ]
