# Generated by Django 4.1.1 on 2022-10-03 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_account_numbers_test_count_account_numbers_test_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='numbers_test_right',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=32),
        ),
        migrations.AlterField(
            model_name='account',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 17, 49, 31, 389533)),
        ),
    ]
