# Generated by Django 4.1.1 on 2022-10-05 06:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_account_numbers_test_right_alter_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='kana_test_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='kana_test_right',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='kana_test_temp',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='account',
            name='kana_test_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='numbers_test_temp',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 9, 47, 31, 344079)),
        ),
    ]
