# Generated by Django 4.1.1 on 2022-10-06 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_account_rating_alter_account_reg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='kana_average_json_array',
            field=models.TextField(default='{"data": []}'),
        ),
        migrations.AddField(
            model_name='account',
            name='kana_average_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='numbers_average_json_array',
            field=models.TextField(default='{"data": []}'),
        ),
        migrations.AddField(
            model_name='account',
            name='numbers_average_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 6, 13, 31, 31, 647406)),
        ),
    ]
